### ISSUE TITLE
Create Start Message? (not that logging has been removed for default)

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#225]
Currently it seems like logging has been disabled, but I haven't confirmed with the devs yet. If so, it would be great to print a simple message to show that telliot is running after the settings are confirmed.

**Comment by oraclown** [comment]
Still happening using this command: `telliot-feeds -a mumbai1 report --rng-auto -p YOLO -wp 240` & latest from main branc (commit `89c5a35b14c0241b4a6f5bd9d17397905dd5f1ba`)

**Comment by oraclown** [comment]
Something wrong with the logging..

Not sure why it's not logging for INFO level stuff and only WARNING and above. I can manually set the level for each logger in `telliot-feeds` like so:
```python
import logging
loggers = [logging.getLogger(name) for name in logging.root.manager.loggerDict]
for logger in loggers:
    if "telliot_feeds" in logger.name:
        logger.setLevel(logging.DEBUG)
 ```
 
 But I have a function that isn't logging to the console if the level is INFO, even though print statements show up, as well as all the loggers in `telliot_feeds` show as set to DEBUG in that function right before I call `logger.info("blah")`
