### ISSUE TITLE
Use local node for CLI datafeed builder tests

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#241]
It's asking for a password and making network requests. This shouldn't happen for the CLI tests. The `GasPriceOracle` sources are tested elsewhere, so we shouldn't be making those network requests in the CLI tests.

To do:
- [ ] Unskip `test_query_parameters`
- [ ] Unskip `test_invalid_query_parameters`
- [ ] Ensure neither above test asks for passwords to run
- [ ] Ensure the reporter reports to locally-deployed oracle
- [ ] Mock any API calls needed, so no network requests needed

**Comment by oraclown** [comment]
The above tests are skipped in this branch: `testing-n-install-fixes`

**Comment by tallywiesenberg** [comment]
Closed with other tests
