### ISSUE TITLE
Add Snapshot CLI manual input

### ISSUE THREAD

**Issue by themandalore** [tellor-io/telliot-feeds#249]

**Comment by akremstudy** [comment]
submitted to oracle snapshot vote results using the cli --build-feed flag (input the proposal id) and the manual input source( for y/n input).  Here is the txn on mumbai: https://mumbai.polygonscan.com/tx/0x4ac60002749c14942974a7a21590152a462dd5bd2ab659e2399d4f0b5b3bc3d0
