### ISSUE TITLE
CERROR   | telliot_core | Exception occurred in telliot-core app

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#256]
start command: `telliot-feeds -a rinkeby3 report -p 25 -wp 120`

`^CERROR   | telliot_core | Exception occurred in telliot-core app
ERROR   | telliot_core | <class 'asyncio.exceptions.CancelledError'>
ERROR   | telliot_core |
ERROR   | telliot_core | ['  File "/home/ubuntu/telliot-work/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 397, in report\n    await reporter.report()\n', '  File "/home/ubuntu/telliot-work/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 441, in report\n    await asyncio.sleep(7)\n', '  File "/usr/lib/python3.9/asyncio/tasks.py", line 652, in sleep\n    return await future\n']`

**Comment by oraclown** [comment]
@tallywiesenberg Reproduce in a test, then add err handling, adjust test

**Comment by oraclown** [comment]
Closing bc this problem hasn't surfaced in awhile
