### ISSUE TITLE
Support New Query Type -- TWAP 

### ISSUE THREAD

**Issue by tallywiesenberg** [tellor-io/telliot-feeds#265]
- [x] Links to [dataSpecs](https://github.com/tellor-io/dataSpecs) issue & new query type file
- [x] Add query type (subclass `AbiQuery`)
- [ ] Add sources (subclass `DataSource`)
- [ ] Add feed (instance of `DataFeed`)
- [ ] Add example instance of the query type to catalog
- [ ] Add support for building custom instances of the new query type (using the `--build-feed` flag)
- [ ] Tests for new query type, sources, feeds, & additions to the CLI
- [ ] Update docs for each addition
- [ ] Include example transactions from a block explorer of new query type submitted to Tellor using `telliot-feeds`

**Comment by oraclown** [comment]
Related data specification for TWAP query type: https://github.com/tellor-io/dataSpecs/blob/main/types/TWAP.md

**Comment by tallywiesenberg** [comment]
No longer implementing, client prefers ETH/USD spot price!
