### ISSUE TITLE
ERROR   | telliot_core | <class 'requests.exceptions.SSLError'> (ethgasstation)

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#266]
Telliot was stable for about 48 hours before I got this error on 2 of 7 reporters. Log attached.
start command: `telliot-feeds -a rinkeby5 report -p 110 -wp 120

[ERROR.txt](https://github.com/tellor-io/telliot-feeds/files/9234256/ERROR.txt)
`

**Comment by oraclown** [comment]
Closing bc handled in [#308](https://github.com/tellor-io/telliot-core/pull/308)
