### ISSUE TITLE
Support report custom SpotPrice query response via CLI

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#275]
- Add a manual feed for SpotPrice to `DATAFEED_BUILDER_MAPPING`
- Submit a custom SpotPrice response to testnet using the `--build-feed` flag & post the tx on this issue

**Comment by akremstudy** [comment]
Txn using cli and manual feed: https://mumbai.polygonscan.com/tx/0x5f7ea03e4088de7140b67d8ff5aa849f39f353ca7291a1d0c0759c1a924974e2
