### ISSUE TITLE
Query data decoder CLI command

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#276]
User should be able to paste in query data from a block explorer and telliot then tells them:
- [x] query type
- [x] parameter names & values
- [ ] parameter types
- [ ] response type
- [ ] link to dataspecs

User can pass encoded reporter submissions to the CLI & get a decoded value:
- [x] User picks query type
- [x] User inputs encoded val, gets decoded val

Behind the scenes it'll probably use `AbiQuery.get_query_from_data()`

**Comment by tallywiesenberg** [comment]
Great idea

**Comment by oraclown** [comment]
Closing bc implemented the main features I was aiming for in above PR^
