### ISSUE TITLE
SSLV3_ALERT_HANDSHAKE_FAILURE]

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#285]
Start command: telliot-feeds -a rinkeby7 report -p 300 -wp 120

[ethgasSSL error.txt](https://github.com/tellor-io/telliot-feeds/files/9282350/ethgasSSL.error.txt)

**Comment by oraclown** [comment]
Closing because we test for this in `telliot-core` [here](https://github.com/tellor-io/telliot-core/blob/main/tests/test_gas.py), but reopen if this comes up again
