### ISSUE TITLE
Stop submissions if address is disputed ( for TellorFlex / Tellor 360 )

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#297]
On TellorFlex / Tellor 360, when an address is disputed only one stake is slashed. The disputed address can continue to report with their remaining stakes. This is a risky situation in the event that an API goes bad and provides incorrect data.

If the address is disputed, telliot should stop reporting and maybe even prompt asking if it should continue. This feature would protect against an event when an API is bad and the reporter is repeatedly submitting bad values accidentally.

**Comment by oraclown** [comment]
probably just return false for the check_reporter_lock if the staker status is no bueno

**Comment by akremstudy** [comment]
Need to add governance contract to monitor if a reporter has been disputed.
The governance contract-abi/address has to be added to telliot-core and should probably be instantiated similar to the oracle contract before the reporter.
tests needed: 
- reporter test- submit bad value, dispute the value on the governance contract, check if reporter is in dispute, spit out a warning message to reporter on telliot.

**Comment by oraclown** [comment]
> Need to add governance contract to monitor if a reporter has been disputed. The governance contract-abi/address has to be added to telliot-core and should probably be instantiated similar to the oracle contract before the reporter. tests needed:
> 
> * reporter test- submit bad value, dispute the value on the governance contract, check if reporter is in dispute, spit out a warning message to reporter on telliot.

Thanks @akremstudy . Sounds like a good plan

**Comment by oraclown** [comment]
If an address is disputed, how do we allow the address to keep reporting for other query types than the one that got them disputed?

**Comment by akremstudy** [comment]
> > Need to add governance contract to monitor if a reporter has been disputed. The governance contract-abi/address has to be added to telliot-core and should probably be instantiated similar to the oracle contract before the reporter. tests needed:
> > 
> > * reporter test- submit bad value, dispute the value on the governance contract, check if reporter is in dispute, spit out a warning message to reporter on telliot.
> 
> Thanks @akremstudy . Sounds like a good plan

@oraclown just learned/realized that a reporter is slashed immediately after a dispute begins (beginDispute on governance contract) so instead of adding governance contract would it feasible to store the stake amount in a variable and pause telliot if the amount decreases?

**Comment by akremstudy** [comment]
something like
```if stake_amount is None:
       amount = get_stake_amount()
       tracked = amount
elif stake_amount != tracked_stake
        msg='disputed msg'
      return

**Comment by oraclown** [comment]
> > > Need to add governance contract to monitor if a reporter has been disputed. The governance contract-abi/address has to be added to telliot-core and should probably be instantiated similar to the oracle contract before the reporter. tests needed:
> > > 
> > > * reporter test- submit bad value, dispute the value on the governance contract, check if reporter is in dispute, spit out a warning message to reporter on telliot.
> > 
> > 
> > Thanks @akremstudy . Sounds like a good plan
> 
> @oraclown just learned/realized that a reporter is slashed immediately after a dispute begins (beginDispute on governance contract) so instead of adding governance contract would it feasible to store the stake amount in a variable and pause telliot if the amount decreases?

Yes, that sounds like the easier implementation.

You could just store the initial stake amount as an attribute of `IntervalReporter`, then wait for user input/confirmation if it decreases and warn them that they may be disputed, and ask if they want to continue reporting.

Tests needed would be similar, just without all the gov contract mocking.

**Comment by oraclown** [comment]
> something like
> 
> ```
>        amount = get_stake_amount()
>        tracked = amount
> elif stake_amount != tracked_stake
>         msg='disputed msg'
>       return```
> ```

Something like that, but make the checking-if-disputed logic into a separate method that is called, so it's easier to test
