### ISSUE TITLE
Add support for interacting with dollar auction integration

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#315]
## Background
A dollar auction project is being developed and this issue is a checklist to make sure we're doing everything required on the Python side to support people interacting w/ the auction on launch..

## Specification
- [x] Report MATIC, TRB, USDC prices. How often each?
- [ ]  ̶D̶o̶ ̶w̶e̶ ̶w̶a̶n̶t̶ ̶t̶h̶e̶ ̶a̶b̶i̶l̶i̶t̶y̶ ̶t̶o̶ ̶p̶l̶a̶c̶e̶ ̶b̶i̶d̶s̶ ̶v̶i̶a̶ ̶t̶h̶e̶ ̶C̶L̶I̶,̶ ̶l̶i̶k̶e̶ ̶`̶t̶e̶l̶l̶i̶o̶t̶-̶f̶e̶e̶d̶s̶ ̶-̶a̶ ̶f̶a̶k̶e̶a̶c̶c̶o̶u̶n̶t̶ ̶i̶n̶t̶e̶g̶r̶a̶t̶i̶o̶n̶s̶ ̶d̶o̶l̶l̶a̶r̶-̶a̶u̶c̶t̶i̶o̶n̶ ̶b̶i̶d̶ ̶-̶-̶a̶m̶o̶u̶n̶t̶ ̶1̶2̶ ̶-̶-̶c̶u̶r̶r̶e̶n̶c̶y̶ ̶U̶S̶D̶ ̶-̶-̶a̶s̶s̶e̶t̶ ̶M̶A̶T̶I̶C̶`̶ ̶?̶ ̶
- [ ]  ̶D̶o̶ ̶w̶e̶ ̶w̶a̶n̶t̶ ̶i̶t̶ ̶t̶o̶ ̶b̶e̶ ̶r̶u̶n̶ ̶a̶n̶d̶ ̶p̶l̶a̶c̶e̶ ̶b̶i̶d̶s̶ ̶a̶u̶t̶o̶m̶a̶t̶i̶c̶a̶l̶l̶y̶ ̶w̶i̶t̶h̶ ̶a̶n̶ ̶u̶p̶p̶e̶r̶ ̶l̶i̶m̶i̶t̶,̶ ̶o̶r̶ ̶b̶a̶s̶e̶d̶ ̶o̶f̶f̶ ̶t̶h̶e̶ ̶s̶i̶z̶e̶ ̶o̶f̶ ̶t̶h̶e̶ ̶p̶o̶t̶?̶
- [ ] ...

Work in progress...

**Comment by tkernell** [comment]
- For report frequency, this would be a good time to test out autopay+tip listener. This dollar auction is an opportunity to test our system as users, so I think we would want telliot to report whenever there's a profit opportunity
- I'm not sure a dollar auction CLI is a priority

**Comment by oraclown** [comment]
> * For report frequency, this would be a good time to test out autopay+tip listener. This dollar auction is an opportunity to test our system as users, so I think we would want telliot to report whenever there's a profit opportunity
> * I'm not sure a dollar auction CLI is a priority

Sounds good. What asset/currency pairs will we need to support for it?

**Comment by tkernell** [comment]
We'll need matic, usdc, and trb
