### ISSUE TITLE
Create NumericApiResponse DataFeed and add to mapping

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#324]
Problem: 
Not all query types are fully supported. Why? Because there ain't an example for `NumericApiResponse` in the `CATALOG_FEEDS` dictionary.

To do:
- create an example `DataFeed` using an instance of the `NumericApiResponse` Query type with parameters that match the example `'numeric-api-response-example` in the query catalog `telliot_feeds.queries.query_catalog`. For the source, use the existing one that submits the query response automatically.
- fix test:
```python
def test_supports_all_active_queries():
        """Make sure all current queries have an associated feed that reporters can use."""
        active_q_tags = [q.tag for q in query_catalog.find()]
    
        for qt in active_q_tags:
>           assert qt in CATALOG_FEEDS
E           AssertionError: assert 'numeric-api-response-example' in {'ampl-legacy': DataFeed(query=LegacyRequest(legacy_id=10), source=AMPLUSDVWAPSource(max_datapoints=256, asset='ampl',...rency='usd', service=<telliot_feeds.sources.price.spot.bittrex.BittrexSpotPriceService object at 0x10a973040>)])), ...}
```

**Comment by wjy7551376** [comment]
HI @oraclown 

Good to see your problem here, I would like to solve this.

**Comment by oraclown** [comment]
> HI @oraclown
> 
> Good to see your problem here, I would like to solve this.

Hey, this one's out of date, but you're welcome to have a go at #322
