### ISSUE TITLE
Support Tellor 360 contracts

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#326]
What needs to be done?

**Comment by oraclown** [comment]
- contract wrapper for Tellor360
- new check stake status method (subgraph?)
- check if need to mint to oracle, console log
- contract wrapper for query data storage contract, so can be used ez in tip listener (maybe not needed)

**Comment by akremstudy** [comment]
@tkernell , still confused about this; is ```stakeAmount``` not current when read directly from the oracle, if not can we calculate the stakeAmount by reading the 12hr TRB price and calculating the stakeAmount?

**Comment by tkernell** [comment]
The stakeAmount read from the oracle is current. It will only be updated when someone calls `updateStakeAmount` manually, assuming there's a new TRB price to be read.

**Comment by akremstudy** [comment]
> The stakeAmount read from the oracle is current. It will only be updated when someone calls `updateStakeAmount` manually, assuming there's a new TRB price to be read.

who is responsible for triggering updateStakeAmount?
from telliot's prespective, instead of events, can we calculate that from reading the TRB price or would that be an issue if updateStakeAmount isn't triggered?

**Comment by tkernell** [comment]
updateStakeAmount can be called by any address, and it's not necessarily anyone's responsibility to either call that function, or report the TRB price. It may be in certain reporters' or users' interest to update the stake amount under different conditions, which could be hard to predict. When the TRB price goes up, perhaps smaller reporters would want to updateStakeAmount so they can report more frequently. We can only speculate at this point.

**Comment by tkernell** [comment]
the `stakeAmount` will only update when `updateStakeAmount` is manually called, so just reading the TRB price won't necessarily tell you the `stakeAmount`. Also, when `updateStakeAmount` is called, it reads the most recent 12+ hour old TRB price. It still may be useful to monitor the reported TRB price in order to predict whether/when the `stakeAmount` is able to change.

**Comment by akremstudy** [comment]
> updateStakeAmount can be called by any address, and it's not necessarily anyone's responsibility to either call that function, or report the TRB price. It may be in certain reporters' or users' interest to update the stake amount under different conditions, which could be hard to predict. When the TRB price goes up, perhaps smaller reporters would want to updateStakeAmount so they can report more frequently. We can only speculate at this point.

Ok, so long that I'm staked, TRB price changes won't affect the frequency that I can report?  Only reason to listen to events  on ```updateStakeAmount``` is to gain certain advantages like increasing reporting frequency.

**Comment by tkernell** [comment]
My reporting frequency is always `12 hours / roundDown(myStakedBalance/stakeAmount)`. So frequency changes whenever `stakeAmount` changes

**Comment by oraclown** [comment]
@akremstudy 's making a 360 reporter that inherits everything from FlexReport and then overwriting the methods that need to be changed. This way we don't change the FlexReporter, and have it just in case

**Comment by oraclown** [comment]
@akremstudy as we discussed on the call, all the reporters should default to 360, so the rng reporter and diva need to be switched over as well, as well as any others. This is the inelegant solution before we implement something better like #313
