### ISSUE TITLE
Make setup easier

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#330]
- [ ] change repo/pkg name to telliot
- [x] change CLI entry point name to telliot, change telliot-core to telliot-core
- [x] move config cmd to telliot/telliot-feeds
- [x] have the cli prompt the user on install for pk and rpc endpoint
- [x] prompts the user to setup chained-accounts as well
- [x] all setup through CLI, reduces need to navigate file system to the /telliot folder

**Comment by oraclown** [comment]
Some of this handled in #377

**Comment by themandalore** [comment]
Confusing default on if you want to change config in CLI (Y/N default is N)
