### ISSUE TITLE
Handle tips that require manual input, skip manual data sources after 10min

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#331]
Query IDs like `[uspce-legacy|gas-price-oracle-example|snapshot-proposal-example|diva-protocol-example|string-query-example]` may require manual inputs from the reporter. 

Currently when these querys are tipped, telliot will pick these up and want to submit for them. This could be an issue for reporters who are not actively watching their reporters. If they are sleeping or away from their computer, telliot is stuck on a prompt for manual input and opportunities to automatically submit for other tips could be lost.

Should there be a flag in telliot to ignore tips/requests for QueryTypes that require manual inputs?

**Comment by oraclown** [comment]
Thanks for this @spuddyminer . I think it should default to running continuously, so adding a flag to allow halts for manual input sounds good.

**Comment by brendaloya** [comment]
Fix- Wait for manual input for 10 minutes and if no answer then skip.
