### ISSUE TITLE
Add Reporting to Arbitrum

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#335]
Add the Network ID and Contract references where necessary to allow reporting to Tellor on Arbitrum.

**Comment by spuddyminer** [comment]
issue closed by pull request #336

**Comment by oraclown** [comment]
spuddy's 2nd report on Abitrum: https://arbiscan.io/tx/0x2fd473c1e8f0ddcfacbb9aa3f64093c121cecc7c3f3b2f522b617860665ae6bb
