### ISSUE TITLE
Exception: Need a mainnet account

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#343]
Error is preventing telliot from starting while trying to report on pulsechain with fresh installation of telliot-feeds. chained accounts and endpoints.yaml seem to be set up correctly for pulsechain, but `telliot-feeds -a account report` results in the following traceback:
```
Traceback (most recent call last):
  File "/root/venv/bin/telliot-feeds", line 5, in <module>
    from telliot_feeds.cli.main import main
  File "/root/venv/lib/python3.9/site-packages/telliot_feeds/cli/main.py", line 13, in <module>
    from telliot_feeds.cli.commands.report import report
  File "/root/venv/lib/python3.9/site-packages/telliot_feeds/cli/commands/report.py", line 17, in <module>
    from telliot_feeds.feeds.tellor_rng_feed import assemble_rng_datafeed
  File "/root/venv/lib/python3.9/site-packages/telliot_feeds/feeds/tellor_rng_feed.py", line 9, in <module>
    from telliot_feeds.sources.blockhash_aggregator import TellorRNGManualSource
  File "/root/venv/lib/python3.9/site-packages/telliot_feeds/sources/blockhash_aggregator.py", line 23, in <module>
    cfg = mainnet_config()
  File "/root/venv/lib/python3.9/site-packages/telliot_feeds/utils/cfg.py", line 23, in mainnet_config
    raise Exception("Need a mainnet account")
Exception: Need a mainnet account
```

Versions:
`telliot-core==0.1.5`
`telliot-feeds==0.1.1`

Troubleshooting steps included:
- Reinstalling telliot-feeds and checking versions.
- adding all infura keys in and verifying pulsechain settings for endpoints.yaml

**Comment by oraclown** [comment]
To close this we need to:
- do a clean install and run through the getting started docs
- make sure those docs are up to date
- if the user is missing an account or node url and key, then the cli should tell them which they're missing.
- it should also suggest using a testnet account, not only mainnet
- It should also link the docs. You could create a couple constants for the docs links that can be reused elsewhere, like `DOCS_GETTING_STARTED_URL`

**Comment by tallywiesenberg** [comment]
> To close this we need to:
> 
> * do a clean install and run through the getting started docs
> * make sure those docs are up to date
> * if the user is missing an account or node url and key, then the cli should tell them which they're missing.
> * it should also suggest using a testnet account, not only mainnet
> * It should also link the docs. You could create a couple constants for the docs links that can be reused elsewhere, like `DOCS_GETTING_STARTED_URL`

I don't think telliot should require that a user have a mainnet account, do you agree? I think it should be this way because some users, such as the pulsechain users, will not plan on using mainnet ethereum. Everything else sounds good

**Comment by oraclown** [comment]
> 

Yes, agree, either a testnet acct or mainnet one

**Comment by oraclown** [comment]
An approach I think might be nicer for the user:
- when no account or config is found, the cli should prompt the user to enter the info needed for a `ChainedAccount`, and also any info needed for a node url (like API key). Under the hood, telliot-feeds/core should add these to the configs. The user shouldn't have to look up what commands to run
- the cli should output what chains are currently supported and link to how to add another
- the cli should link to more info on `ChainedAccount`s as well and let the user now what files are saved
