### ISSUE TITLE
telliot stops when internet connection is lost

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#39]
When the internet connection is lost, the telliot process stops running.

Expected behavior is that telliot would keep running until internet connection is reestablished then resume the process.

See attached for log with the traceback. (feel free to ping me in discord if attachment doesn't work) 
[log.txt](https://github.com/tellor-io/telliot-feed-examples/files/7620766/log.txt)

**Comment by tallywiesenberg** [comment]
Two approaches I can think of:
https://stackoverflow.com/questions/52398769/stop-python-script-aborting-when-there-is-no-internet-connection
or 
catch the exception given from the log
@oraclown thoughts?

**Comment by oraclown** [comment]
The stackoverflow one makes sense. I'd async try three different ip addresses though, not just google. then add that function to the reporter maybe and have it run each time before it does `report_once()`. Add logging ofc
