### ISSUE TITLE
Have Tip listener Listen for Tellor360 Time Based Rewards

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#411]
Currently telliot can listen for tips from the Autopay contract. This is great! But, to track profitability on Tellor 360 mainnet it should be able to get the time based rewards also.

This may be a simple fix, but the version that I hacked together to report to the 360 contracts on goerli is not picking up on the time based rewards. thanks for reading!

**Comment by tallywiesenberg** [comment]
Closed with #415
