### ISSUE TITLE
Very High Gas Use / Estimation

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#417]
Telliot currently uses A LOT of gas sometimes on goerli and mainnet 
example transaction (submitted with 800+ gwei gas): https://etherscan.io/tx/0x1b5beb4b79877d6f8bd185461c8039040fd517449f0f78d5a3b282213f17fc6c

**Comment by oraclown** [comment]
I think @akremstudy took care of this in #420  (nice)
