### ISSUE TITLE
tries to report for unsupported spot prices without checking reporter lock

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#460]
@spuddyminer Can you add more details?

**Comment by spuddyminer** [comment]
Expected behavior: Telliot waits until it's out of reporter lock before trying to report for a tip that requires manual value.

Observed behavior: Telliot prompts the user for submission even though the reporter's address may still be in time lock, causing a failed transaction.

**Comment by oraclown** [comment]
I added a test to try and simulate this, but couldn't reproduce the behavior. Feel free to reopen if this comes up again, sire
