### ISSUE TITLE
Support reporting based on price threshold

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#468]
A user should be able to pick a certain asset/currency pair, and then report this price on an interval, if it's profitable, OR if the current price deviates from the latest retrieved from Tellor by a certain percentage

**Comment by akremstudy** [comment]
test for pricethreshold check: https://github.com/tellor-io/telliot-feeds/blob/f21495edcb2aee0b94a81e271d8281e9081035fb/tests/tips/test_selected_queryid.py#L126
