### ISSUE TITLE
Add Option for Cycle through catalog (ignore tips / tip listener)

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#480]
Telliot is getting very good at profitability, but this has actually created a problem for testing.

Currently the only way to get all the spot prices reported without running a separate telliot for each one with the `-qt` and `-p YOLO` flags. It would be great for testnets to have the option to ignore profitability _and also_ the tip listener. 

This way one telliot instance would be able to report all the built in prices every day automatically for the sake of keeping the databases fresh.

**Comment by LP-Crypto-Scholar** [comment]
Yeah good idea. I used to report the whole catalogue but since 360 upgrade have changed to eth usd only as a risk mitigation measure until I sort out api verification. Am keen to go back to running a full catalogue asap though so would use this function in the future
