### ISSUE TITLE
New Binance API Warning message

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#481]
Telliot logs are showing an error message responce from the binance API that we use for some price feeds.  The kinds of use Binance API allows may have changed. Suggest looking into it so we don't have any data quality problems. 

Please comment and let me know if this warning isn't easily reproduced, as it might just be a problem with my VM that's running many telliots. 

The warning message:

`WARNING | telliot_feeds.sources.price.spot.binance | Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error.`

**Comment by oraclown** [comment]
Solution is to use a VPN out of Binance's newly restricted countries. You get this if your IP is in
`a Restricted Location. For the purposes hereof, “Restricted Location” shall include the United States, Malaysia, Ontario (Canada), and`
I tested using a Mexico IP addr and don't get it, but do when I switch to USA IP.
More info under "Eligibility" in their new [terms of service](https://www.binance.com/en/terms)
