### ISSUE TITLE
Polygon Send Transaction frequently Fails 

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#482]
I can't put my finger on when it started, but a telliot instance that reports on Polygon has been getting stuck unable to submit because of `replacement transaction underpriced` messages. This might just be an RPC problem and I'm looking into it, but creating the issue just in case.

After starting telliot, it will submit as expected until a submit value transaction fails with this error message. After one fail, telliot does not recover and the error message / failed submissions repeat until the instance is restarted. After restart there will be one or two successful submissions, then the fails start again.

Note: this only happens on Polygon mainnet.

```
DEBUG   | telliot_feeds.reporters.interval | Sending submitValue transaction
ERROR   | telliot_feeds.reporters.interval | Send transaction failed: ValueError({'code': -32000, 'message': 'replacement transaction underpriced'})
```

**Comment by oraclown** [comment]
heard this no longer occurs
