### ISSUE TITLE
Multicall Error (KeyError: ('values_array', b'\\\x13\xcd\x)

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#499]
This is a new error that stops telliot from running.

Start command: telliot -a mumbai5 report -wp 300
Versions:
telliot-core: #a692d532061cef0af59b01c9fb75aca5ac9f7954
telliot-feeds: #f6c8757f11edcb74dee1f65adab2d84de1d9c148

log:
[multicall error.txt](https://github.com/tellor-io/telliot-feeds/files/10279890/multicall.error.txt)

**Comment by oraclown** [comment]
Duplicate of #484

**Comment by spuddyminer** [comment]
closed, because it's a duplicate of #484
