### ISSUE TITLE
ValueError: {'code': -32603, 'message': 'request failed or timed out'} (Bitfinex API problem?)

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#532]
start command: `telliot -a polygon1 report -p -10 -wp 120`
versions:
`telliot-core==0.1.7`
`telliot-feeds @cabc0f288625ad04223988034d1ba14a89a48824#`

log:
[error log.txt](https://github.com/tellor-io/telliot-feeds/files/10337803/error.log.txt)

**Comment by oraclown** [comment]
duplicate of #531

**Comment by spuddyminer** [comment]
closed cause duplicate
