### ISSUE TITLE
diva & numeric api rsp feeds break when randomly selected?

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#588]
more info [here](https://github.com/tellor-io/telliot-feeds/pull/586#pullrequestreview-1279934493)

**Comment by akremstudy** [comment]
Sorry if the comment wasn't clear but I was talking about the break happening pre the try/catch error handling.  Pointing out that the core issue might've been coming from when those feeds were randomly selected during telliot rotations.

**Comment by oraclown** [comment]
I propose we just address it when something else breaks, and in the meantime get [#587 ](https://github.com/tellor-io/telliot-feeds/pull/587) to a state where it can be merged.
