### ISSUE TITLE
oracle contract function out of date / slightly incorrect?

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#594]
`getDataBefore` is different in this repo and in the [Solidity docs](https://docs.tellor.io/tellor/getting-data/solidity-integration#reading-data)

return vals in the Solidity docs:
```js
(bytes memory _value, uint256 _timestampRetrieved) =
          getDataBefore(_queryId, block.timestamp - 20 minutes);
```
contract code in our py repo:
```js
function getDataBefore(bytes32 _queryId, uint256 _timestamp)
        public
        view
        returns (
            bool _ifRetrieve,
            bytes memory _value,
            uint256 _timestampRetrieved
        )
```

**Comment by akremstudy** [comment]
thats cause the solidity docs are referencing the function with the same name in [UsingTellor.sol](https://github.com/tellor-io/usingtellor/blob/cfc56240e0f753f452d2f376b5ab126fa95222ad/contracts/UsingTellor.sol#L58-L67) whereas the contract [Tellorflex.sol](https://github.com/tellor-io/tellorFlex/blob/3b3820f2111ec2813cb51455ef68cf0955c51674/contracts/TellorFlex.sol#L437-L454) has a slightly different getDataBefore function.
