### ISSUE TITLE
Ampleforth Custom VWAP Error

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#597]
start command: telliot report -a mumbai3 -rf -p YOLO -wp 1800

Seems like what happened is that telliot was not able to get the trading volume / prices from Bitfinex for the AMPL VWAP calculation, and telliot submitted a value that was incorrect. (submitted value was $1.74, should be around $1.04.) Just dumping the log here for now. 

Suggested fix: if there are errors from the API, don't submit.

Let me know if more information is needed 🙏

```
Bitfinex trades for tAMPUSD: 930
Bitfinex trades for AMPL_UST: 0
Could not get Bitfinex trades for AMPL_UST
Bitfinex trades for UST_USD: 0
Could not get Bitfinex trades for UST_USD
Bitfinex trades for AMPL_BTC: 0
Could not get Bitfinex trades for AMPL_BTC
Bitfinex trades for BTC_USD: 0
Could not get Bitfinex trades for BTC_USD
INFO    | telliot_feeds.sources.ampleforth.ampl_usd_vwap | Nubmer of sources used for AMPL/USD VWAP: 2
INFO    | telliot_feeds.sources.ampleforth.ampl_usd_vwap | AMPL/USD VWAP 1.7436210852981011 retrieved at time 2023-02-13 18:55:04.297309+00:00
DEBUG   | telliot_feeds.reporters.interval | IntervalReporter Encoded value: 0000000000000000000000000000000000000000000000001832962394130b7a
DEBUG   | telliot_feeds.reporters.interval | Sending submitValue transaction
INFO    | telliot_feeds.reporters.interval | View reported data: 
https://mumbai.polygonscan.com//tx/0x0ec0a0178f02498a9acf9bfeb9295ea7d4ab475aaad8871ef9eac8bbf6f9ee6b
INFO    | telliot_feeds.reporters.interval | Sleeping for 1800 seconds
```

**Comment by oraclown** [comment]
I'm trying to make more tests for this. How do I reproduce a bunch of correct prices for a set of start-end windows? Where are you getting your correct prices? cc @akremstudy

**Comment by spuddyminer** [comment]
Not sure how helpful this information is, but the way the Anyblock API worked it only updated once a day around midnight UTC...maybe the data is only available at the end of the day? Also, it was always very close to BraveNewCoin's value for AMPL VWAP too.
