### ISSUE TITLE
Latest version does not support tellor-flex contracts

### ISSUE THREAD

**Issue by Trick03** [tellor-io/telliot-feeds#616]
Hi 

It seems the latest version (0.1.7) does not support tellor-flex properly as we try do what stated in the [Document](https://tellor-io.github.io/telliot-feeds/usage/) and run the command `telliot report -flex -a myacct1 -qt pls-usd-spot -p YOLO` or `telliot report -a myacct1  -flex` and it throws an error.

`tenv/lib/python3.9/site-packages/telliot_feeds/cli/commands/report.py", line 489, in report
    reporter = TellorFlexReporter(
TypeError: __init__() got an unexpected keyword argument 'use_random_feeds'` 

kindly see below details for reference for all the version we use upon running the said service

> aiohttp==3.8.3
> aiosignal==1.2.0
> async-timeout==4.0.2
> attrs==22.1.0
> base58==2.1.1
> bitarray==2.6.0
> certifi==2022.9.24
> chained-accounts==0.0.1
> charset-normalizer==2.1.1
> clamfig==0.1.3
> click==8.1.3
> cytoolz==0.12.0
> eth-abi==2.2.0
> eth-account==0.5.9
> eth-hash==0.5.0
> eth-keyfile==0.5.1
> eth-keys==0.3.4
> eth-retry==0.1.13
> eth-rlp==0.2.1
> eth-typing==2.3.0
> eth-utils==1.9.5
> frozenlist==1.3.1
> hexbytes==0.3.0
> idna==3.4
> ipfshttpclient==0.8.0a2
> jsonschema==3.2.0
> lru-dict==1.1.8
> multiaddr==0.0.9
> multicall==0.7.0
> multidict==6.0.2
> netaddr==0.8.0
> parsimonious==0.8.1
> protobuf==3.20.3
> pycryptodome==3.15.0
> pydantic==1.10.5
> pyrsistent==0.19.2
> python-dotenv==0.21.0
> PyYAML==6.0
> requests==2.28.1
> rlp==2.0.1
> simple-term-menu==1.5.2
> six==1.16.0
> telliot-core==0.2.2
> telliot-feeds==0.1.7
> toolz==0.12.0
> typing_extensions==4.4.0
> urllib3==1.26.12
> varint==1.0.2
> web3==5.28.0
> websockets==9.1
> yarl==1.8.1

kindly advice if we miss something on the configuration part or the way we run it.

Just for the reference we were able to run a reporter on the old version before

> telliot_core-0.1.5.dist-info
> telliot_feeds-0.1.1.dist-info

Appreciate your great help on this

**Comment by oraclown** [comment]
> Hi
> 
> It seems the latest version (0.1.7) does not support tellor-flex properly as we try do what stated in the [Document](https://tellor-io.github.io/telliot-feeds/usage/) and run the command `telliot report -flex -a myacct1 -qt pls-usd-spot -p YOLO` or `telliot report -a myacct1 -flex` and it throws an error.
> 
> `tenv/lib/python3.9/site-packages/telliot_feeds/cli/commands/report.py", line 489, in report reporter = TellorFlexReporter( TypeError: __init__() got an unexpected keyword argument 'use_random_feeds'`
> 
> kindly see below details for reference for all the version we use upon running the said service
> 
> > aiohttp==3.8.3
> > aiosignal==1.2.0
> > async-timeout==4.0.2
> > attrs==22.1.0
> > base58==2.1.1
> > bitarray==2.6.0
> > certifi==2022.9.24
> > chained-accounts==0.0.1
> > charset-normalizer==2.1.1
> > clamfig==0.1.3
> > click==8.1.3
> > cytoolz==0.12.0
> > eth-abi==2.2.0
> > eth-account==0.5.9
> > eth-hash==0.5.0
> > eth-keyfile==0.5.1
> > eth-keys==0.3.4
> > eth-retry==0.1.13
> > eth-rlp==0.2.1
> > eth-typing==2.3.0
> > eth-utils==1.9.5
> > frozenlist==1.3.1
> > hexbytes==0.3.0
> > idna==3.4
> > ipfshttpclient==0.8.0a2
> > jsonschema==3.2.0
> > lru-dict==1.1.8
> > multiaddr==0.0.9
> > multicall==0.7.0
> > multidict==6.0.2
> > netaddr==0.8.0
> > parsimonious==0.8.1
> > protobuf==3.20.3
> > pycryptodome==3.15.0
> > pydantic==1.10.5
> > pyrsistent==0.19.2
> > python-dotenv==0.21.0
> > PyYAML==6.0
> > requests==2.28.1
> > rlp==2.0.1
> > simple-term-menu==1.5.2
> > six==1.16.0
> > telliot-core==0.2.2
> > telliot-feeds==0.1.7
> > toolz==0.12.0
> > typing_extensions==4.4.0
> > urllib3==1.26.12
> > varint==1.0.2
> > web3==5.28.0
> > websockets==9.1
> > yarl==1.8.1
> 
> kindly advice if we miss something on the configuration part or the way we run it.
> 
> Just for the reference we were able to run a reporter on the old version before
> 
> > telliot_core-0.1.5.dist-info
> > telliot_feeds-0.1.1.dist-info
> 
> Appreciate your great help on this

Thanks for reporting this bug, @Trick03 . We'll get back to you soon with next steps or a fix!

**Comment by brendaloya** [comment]
@Trick03 Please update to the latest Tellor contracts.
