### ISSUE TITLE
Trigger Submissions based on Arbitrary events (e.g. n% change in spot price)

### ISSUE THREAD

**Issue by 0xSpuddy** [tellor-io/telliot-feeds#617]
When a user calls setupDataFeed on one of the Tellor Autopay contracts, they may specify a `priceThreshold`. When priceThreshold is used, tips will be paid to the reporter who makes a submission when the value is the n% different from the previous value, where "n" is the percentage specified by the user.

This is awesome! But, it would be great if telliot could do that off-chain (even if there's no Autopay tips). This issue is requests the addition of submission triggers based on various arbitrary events like a percent change in the value of a spot price asset. Other arbitrary event type triggers may include on-chain events. @themandalore had more ideas for these, so I'll ask him to comment here also 🙏

**Comment by spuddyminer** [comment]
Talked to @akremstudy and autopay priceThresholds should already be picked up on the tip listener. I've just never tested it, so I'll work on that next.
