### ISSUE TITLE
Add Source: Balancer

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#630]
To provide price data for stETH, rETH and WstETH we will need more sources. The sources for these prices are mostly going to be the DEXs, because these assets are traded predominantly on-chain.  Balancer has pools for all three assets, so we should look at adding it as a price source. https://balancer.fi/

**Comment by akremstudy** [comment]
Added sources (curvefi, lido) to support these assets, maybe we can add this at a later time.
