### ISSUE TITLE
Add Source: Lido

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#631]
As more users reach out building protocols that use stETH and WstETH as collateral, we will need more sources for the price and conversion rates of these assets. Are we able to use Lido directly to pull the prices?  https://docs.lido.fi/

**Comment by akremstudy** [comment]
Added [here](https://github.com/tellor-io/telliot-feeds/blob/main/src/telliot_feeds/sources/wsteth_source.py)
