### ISSUE TITLE
-pwd flag should also work for deposit more TRB when disputed

### ISSUE THREAD

**Issue by 0xSpuddy** [tellor-io/telliot-feeds#639]
This is a wish list issue to allow Telliot to run more "automatically". 

In the tellor system, when an address is disputed the frequency of reports is reduced / time between reports is increased. When the `-s` flag is used in Telliot, this can be avoided by holding extra TRB that can replace the disputed stakes, allowing the reporter to continue as before in a dispute griefing situation. It's in the reporters interest to keep submitting as long as they've been submitting good values. (they rake in the disputers fees) (I hope that makes sense.)

Currently, setting the `-pwd` flag works great for skipping the password check when telliot starts, but telliot is still prompting for password when the address is disputed and the `-s` flag is set. I think that Telliot should skip this password check as well so that reporting can continue automatically.
If this doesn't make sense, please comment with questions and I can provide more information. Thanks for reading! 

versions:
telliot-core.git@e97fae2a6c6365b7671252b220cc1bd95c969572
telliot-feeds.git@51332dcd202e59ace099ac414b480cce3dbb485f

**Comment by themandalore** [comment]
add flag if you're going to auto restake

**Comment by 0xSpuddy** [comment]
thinking about closing this one, because in hindsight this is a bad idea...
