### ISSUE TITLE
Crash out with error "Read timed out. (read timeout=None)"

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#666]
start command: `telliot report -a goerli5 -pwd asdf -p 20 -wp 10`
versions:
telliot-core==0.2.5
telliot-feeds #54908ccba1ed65a2cbfd2062418266d661242e76

log:
[read timeout log.txt](https://github.com/tellor-io/telliot-feeds/files/11312071/read.timeout.log.txt)

**Comment by tallywiesenberg** [comment]
It appears this is an uncaught exception in the `is_online` reporter utility. Patching now

**Comment by akremstudy** [comment]
this was already fixed and merged by this pr #668
