### ISSUE TITLE
Crashout W/ error "asyncio.exceptions.TimeoutError"

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#671]
start command: `telliot report -a polygon2 -wp 60`
versions: 
telliot-core #19cc8684bd5bdba181045a526b53f18621886724
telliot-feeds #e03d2bfc24afe4ae8780262e59f64732924ddc7c

log attached: 
[crashout.txt](https://github.com/tellor-io/telliot-feeds/files/11354117/crashout.txt)

**Comment by akremstudy** [comment]
this error is handled with current version of repo.
